DROP TABLE IF EXISTS dwarves;
DROP TABLE IF EXISTS clan;
DROP TABLE IF EXISTS beardColors;
DROP TABLE IF EXISTS occupations;
DROP TABLE IF EXISTS favWeapons;
DROP TABLE IF EXISTS favDrinks;
CREATE TABLE IF NOT EXISTS dwarves(
dwarfId INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
height TEXT,
beardLength INTEGER,
clanId INTEGER,
beardColorId INTEGER,
occupationId INTEGER,
favWeaponId INTEGER,
favDrinkId INTEGER
);

CREATE TABLE IF NOT EXISTS clan(
clanId INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);

CREATE TABLE IF NOT EXISTS beardColors(
beardColorId INTEGER PRIMARY KEY AUTOINCREMENT,
color TEXT
);

CREATE TABLE IF NOT EXISTS occupations(
occupationId INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);
CREATE TABLE IF NOT EXISTS favWeapons(
favWeaponId INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);
CREATE TABLE IF NOT EXISTS favDrinks(
favDrinkId INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);